# Generated by Django 4.2.2 on 2023-06-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('Precio', models.FloatField()),
                ('codigo', models.CharField()),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
    ]
