# Generated by Django 4.2.2 on 2023-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20230710_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=20)),
                ('nombre_autor', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('Precio', models.FloatField()),
                ('codigo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
